config/routes.rb
Music::Application.routes.draw do
  get "notes/create"

  get "notes/new"

  get "notes/destroy"

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks do
    resources :notes, only: [:create]
  end

  resources :notes, only: [:destroy]

  resources :users, except: [:show] do
    member do
      delete :logout
    end
    collection do
      get :activate
      post :login
    end
  end

  root to: "bands#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :name, :recording_type

  belongs_to :band
  has_many :tracks, dependent: :destroy

  validates :name, :band_id, :recording_type , presence: true
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums

  validates :name, presence: {name: 'must contain name'}
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :track_id, :user_id
  belongs_to :track
  validates :body, presence: true

  belongs_to :user
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :name, :bonus, :lyrics

  belongs_to :album
  has_one :band, through: :album
  has_many :notes, dependent: :destroy

  validates :name, :album_id, :bonus, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password_confirmation
  attr_accessible :admin, :email, :password, :password_confirmation, :token, :active
  has_many :notes
  validates :email, uniqueness: true, presence: true
  validates_confirmation_of :password

  before_create :make_token

  def logout
    self.token = nil
    save
  end

  def make_token
    self.token = SecureRandom.base64
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    @bands = Band.all
  end

  def create
    @album = Album.new(params[:album])

    if @album.save
      redirect_to @album
    else
      @bands = Band.all
      render :new
    end
  end

  def edit
    @bands = Band.all
  end

  def update
  end

  def destroy
    if user_is_admin?
      @album.destroy

      flash[:notice] = "Successfully deleted #{@album.name}"
      redirect_to bands_url
    else
      flash[:alert] = "You're not allowed"
      redirect_to root_url
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_object, only: [:show, :edit, :update, :destroy]

  include ApplicationHelper

  def get_object
    model = self.class.to_s.gsub(/Controller/, '').singularize.constantize
    instance_variable_set("@#{model.to_s.downcase}", model.find(params[:id]))
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController


  def index
    @bands = Band.all
  end

  def show
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(params[:band])

    if @band.save
      redirect_to @band
    else
      render :new
    end
  end

  def edit

  end

  def update
  end

  def destroy
    if user_is_admin?
      @band.destroy

      flash[:notice] = "Successully deleted #{@band.name}"
      redirect_to bands_url
    else
      flash[:alert] = "You're not allowed"
      redirect_to root_url
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(params[:note])

    if @note.user_id != current_user.id
      flash[:alert] = "Can only create notes for currently logged in user"
      redirect_to root_url
    elsif @note.save
      flash[:notice] = "Note saved successfully"
      redirect_to @note.track
    else
      flash[:alert] = "Note not saved!"
      redirect_to @note.track
    end
  end

  def destroy
    @note.destroy

    flash[:notice] = "Successfully deleted the note"
    redirect_to @note.track
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Track.all
  end

  def show
  end

  def new
    @track = Track.new(album_id: params[:album_id])
    @albums = Album.all
  end

  def create
    @track = Track.new(params[:track])

    if @track.save
      redirect_to @track
    else
      @albums = Album.all
      render :new
    end
  end

  def edit
    @albums = Album.all
  end

  def update
  end

  def destroy
    if user_is_admin?
      @track.destroy

      flash[:notice] = "Successfully deleted #{@track.name}"
      redirect_to bands_path
    else
      flash[:alert] = "You are not allowed!"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def activate
    user = User.find_by_token!(params[:token])

    if user.token == params[:token]
      user.active = true
      user.save

      session[:token] = user.token

      flash[:notice] = "Account activated successfully!"
      redirect_to root_url
    else
      flash[:alert] = "Unable to verify your account."
      redirect_to root_url
    end
  end

  def index
    @users = User.all
  end

  def login
    @user = User.find_by_email(params[:email])

    if @user && (@user.password == params[:password]) && @user.active
      @user.make_token
      @user.save
      session[:token] = @user.token

      flash[:notice] = "Logged in successfully as #{@user.email}"
      redirect_to root_url
    elsif @user && !@user.active
      flash[:alert] = "Check your email for an activation code!"
      redirect_to root_url
    else
      flash[:alert] = "Wrong email/password combination"
      redirect_to root_url
    end
  end

  def logout
    current_user.logout
    session[:token] = nil

    redirect_to root_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      msg = UserMailer.welcome_email(@user)
      msg.deliver!

      flash[:notice] = "Successfully created new user"
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    @user.destroy

    flash[:notice] = "User deleted"
    redirect_to :root_path
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find_by_token(session[:token]) if session[:token]
  end

  def logged_in?
    !!current_user
  end

  def user_is_admin?
    current_user && current_user.admin
  end

  def ugly_lyrics(lyrics)
    "<pre>#{lyrics.split("\n").map { |line| "&#9835; " + line }.join}</pre>".html_safe
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/_form.html.erb
<form action="/albums<%= "/#{@album.id }"%>" method="post">

  <label for="album_name">Name</label>
  <input type="text" name="album[name]" id="album_name">
  <br>

  <label for="album_type">Type</label>
  <select name="album[recording_type]" id="album_type">
    <option value="live">Live</option>
    <option value="studio">Studio</option>
  </select>
  <br>

  <label for="album_band_id">Band</label>
  <select name="album[band_id]" id="album_band_id">
    <option>Select</option>
    <% @bands.each do |band| %>
    <option value="<%= band.id %>" <%= 'selected' if band.id == @album.band_id %>><%= band.name %></option>
    <% end %>
  </select>
  <br>

  <% if @album.id %>
  <input type="hidden" name="_method" value="put">
  <% end %>
  <br>

  <input type="submit" value="<%= controller.action_name == 'edit' ? 'Update' : 'Save' %>">

</form>

app/views/albums/edit.html.erb
<h2>Edit Album</h2>

<%= render partial: "form" %>

app/views/albums/index.html.erb
<h2>Albums</h2>

<% if @albums.empty? %>
<p>NO ALBUMS</p>
<% end %>

<% @albums.each do |album| %>
  <%= link_to album.name, album %>
<% end %>
<br>
<%= link_to 'Create new album', new_album_url %>

app/views/albums/new.html.erb
<h2>New Album</h2>

<%= render partial: "form" %>

app/views/albums/show.html.erb
<h5> <%= link_to @album.band.name, @album.band %> > <%= @album.name %></h5>
<h2><%= @album.name %></h2>

<ol>
<% @album.tracks.each do |track| %>
  <li><%= link_to track.name, track %> <%= render partial: "shared/destroy_button", locals: {object: track} %></li>
<% end %>
</ol>
<br>
<br>
<%= link_to "Add new track", new_album_track_url(@album) %>

app/views/bands/_form.html.erb
<form action="/bands<%= "/#{@band.id}" %>" method="post">

  <label for="band_name">Name</label>
  <input type="text" name="band[name]" id="band_name">
  <br>

  <% if @band.id %>
  <input type="hidden" name="_method" value="put">
  <% end %>
  <br>

  <input type="submit" value="<%= controller.action_name == 'edit' ? 'Update' : 'Save' %>">

</form>

app/views/bands/edit.html.erb
<h2>Edit Band</h2>

<%= render partial: "form" %>

app/views/bands/index.html.erb
<h2>Bands</h2>

<% if @bands.empty? %>
<p>NO BANDS</p>
<% end %>

<ol>
<% @bands.each do |band| %>
  <li><%= link_to band.name, band %></li>
<% end %>
</ol>

<%= link_to 'Create new band', new_band_url %>

app/views/bands/new.html.erb
<h2>New Band</h2>

<%= render partial: "form" %>

app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

<ol>
<% @band.albums.each do |album| %>

  <li><%= link_to album.name, album %> <%= render partial: "shared/destroy_button", locals: {object: album} %></li>
  <ol>
    <% album.tracks.each do |track| %>
    <li><%= link_to track.name, track %> <%= render partial: "shared/destroy_button", locals: {object: track} %></li>
    <% end %>
  </ol>
<% end %>
</ol>
<%= link_to "Create new album", new_band_album_url(@band) %>
<%= render partial: "shared/destroy_button", locals: {object: @band} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  html{
    font-family: helvetica, sans-serif;
  }
  </style>
</head>
<body>
<%= debug params %>
<%= debug session %>
<hr>

<p><%= flash[:notice] %></p>
<p><%= flash[:alert] %></p>

<% if logged_in? %>
<span>Logged is as <%= current_user.email %> <%= render partial: "shared/logout"  %></span>
<% else %>
<%= render partial: "shared/login" %>
<% end %>


<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<form action="<%= track_notes_url(track) %>" method="post">
  <label for="note_body">Add a note</label>
  <textarea name="note[body]" id="note_body"></textarea>
  <input type="hidden" name="note[track_id]" value="<%= track.id %>">
  <input type="hidden" name="note[user_id]" value="<%= current_user.id %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Save">
</form>

app/views/notes/_note.html.erb
<li><%= note.user.email %> says: <%= note.body %>
<% if current_user.id == note.user_id || user_is_admin? %>
<%= render partial: "shared/destroy_button", locals: { object: note } %></li>
<% end %>

app/views/shared/_destroy_button.html.erb
<% if user_is_admin? || object.class == Note %>
<form action="<%= send("#{object.class.to_s.downcase}_url".to_sym, object) %>" method="post">

  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete">
</form>
<% end %>

app/views/shared/_login.html.erb
<form action="<%= login_users_url %>" method="post">
  <input type="text" placeholder="Email" name="email">
  <input type="password" placeholder="Password" name="password">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Log in">
</form>

app/views/shared/_logout.html.erb
<form action="<%= logout_user_url(current_user) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Logout">
</form>

app/views/tracks/_form.html.erb
<form action="/tracks<%= "/#{@track.id}"%>" method="post">

  <label for="track_name">Track Name</label>
  <input type="text" name="track[name]" id="track_name">
  <br>

  <label for="track_bonus">Type</label>
  <select name="track[bonus]" id="track_bonus">
    <option value="bonus">Bonus</option>
    <option value="regular" selected>Regular</option>
  </select>
  <br>

  <label for="track_album_id">Album</label>
  <select name="track[album_id]" id="track_album_id">
    <option>Select</option>
    <% @albums.each do |album| %>
    <option value="<%= album.id %>" <%= 'selected' if @track.album_id == album.id %>><%= album.name %></option>
    <% end %>
  </select>
  <br>

  <label for="track_lyrics">Lyrics</label>
  <textarea name="track[lyrics]" id="track_lyrics">
    <%= @track.lyrics %>
  </textarea>
  <% if @track.id %>
  <input type="hidden" name="_method" value="put">
  <% end %>
  <br>
  <br>

  <input type="submit" value="<%= controller.action_name == 'edit' ? 'Update' : 'Save' %>">

</form>

app/views/tracks/edit.html.erb
<h2>Edit Track</h2>

<%= render partial: "form" %>

app/views/tracks/index.html.erb
<h2>Tracks</h2>

<% if @tracks.empty? %>
<p>NO TRACKS</p>
<% end %>

<% @tracks.each do |track| %>
  <%= link_to track.name, track %>
<% end %>

<%= link_to 'Create new track', new_track_url %>

app/views/tracks/new.html.erb
<h2>New Track</h2>

<%= render partial: "form" %>

app/views/tracks/show.html.erb
<h5>
  <%= link_to @track.album.band.name, @track.album.band %> > <%= link_to @track.album.name, @track.album %> > <%= @track.name %>
</h5>

<%= ugly_lyrics(@track.lyrics) %>

<h2><%= @track.name %></h2> <%= render partial: "shared/destroy_button", locals: {object: @track} %>
<%= render @track.notes %>
<% if current_user %>
<%= render partial: "notes/form", locals: {track: @track} %>
<% end %>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <input type="email" name="user[email]" placeholder="email">
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <label for="password_confirm">Confirm Password</label>
  <input type="password" name="user[password_confirmation]" id="password_confirm">
  <input type="hidden" name="authenticty_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Sign Up!">
</form>